Repository Team-Crops/fit-web, pull requests merged in 2024-01, with the labels that each got.

#14 `Toggle` 컴포넌트 추가
  src/components/atoms/Toggle.tsx
  src/stories/Toggle.stories.tsx
Labels: ✨ feature

#13 `CheckBox` 컴포넌트 추가
  .pnp.cjs
  .storybook/main.ts
  next.config.js
  package.json
  src/assets/icons/check.svg
  src/components/atoms/CheckBox.tsx
  src/stories/CheckBox.stories.tsx
  yarn.lock
Labels: ✨ feature

#15 Add icons component
  src/assets/icons/arrow-forward.svg
  src/components/atoms/Icons.tsx
Labels: ✨ feature

#28 Fix typo6 letter-spacing of Txt
  src/components/atoms/Text.tsx
Labels: 🐛 bug

#32 SVG 파일에 `color` 속성이 적용되도록 수정
  src/assets/icons/arrow-forward.svg
  src/assets/icons/arrow-right.svg
  src/assets/icons/away.svg
  src/assets/icons/check.svg
  src/assets/icons/click.svg
  src/assets/icons/cross.svg
  src/assets/icons/logo.svg
  src/assets/icons/run.svg
  src/components/atoms/Icons.tsx
Labels: 🛠️ refactor

#30 Add Divider component
  src/components/atoms/Divider.tsx
Labels: ✨ feature

#37 누락된 아이콘 이미지 추가
  src/assets/icons/google.svg
  src/assets/icons/kakao.svg
Labels: 🐛 bug
