Repository Team-Crops/fit-web, pull requests merged in 2024-06, with the labels that each got.

#134 배포 알림 끄기
  .github/workflows/discord.yml
Labels: ⚙️ cicd

#132 마이페이지 버그 수정
  src/app/mypage/page.tsx
  src/components/molecules/MyPage/RegisterPortfolioBlock.tsx
  src/components/organisms/MyPage/ActivityEdit.tsx
  src/components/organisms/MyPage/MemberInfoEdit.tsx
  src/components/organisms/MyPage/PortfolioEdit.tsx
  src/components/templates/MyPage/InfoEditSection.tsx
  src/components/templates/MyPage/MyInfoSection.tsx
Labels: 🐛 bug

#133 `<Footer />` 링크 주소 올바르게 변경하기
  .env.example
  src/components/organisms/FooterContent.tsx
Labels: 🐛 bug

#139 신고하기, 강퇴하기 기능 추가
  src/app/globals.css
  src/assets/icons/emoji-police-car-light.png
  src/assets/icons/index.ts
  src/components/atoms/Button.tsx
  src/components/atoms/ConfirmationDialog.tsx
  src/components/atoms/Icons.tsx
  src/components/atoms/MouseDetector.tsx
  src/components/atoms/Text.tsx
  src/components/atoms/Tooltip.tsx
  src/components/atoms/index.ts
  src/components/molecules/ChatParticipant.tsx
  src/components/molecules/ChatPositionGroup.tsx
  src/components/molecules/ReportPopup.tsx
  src/components/organisms/ChatParticipants.tsx
  src/components/organisms/ChatRoom.tsx
  src/components/organisms/SignUpCompletePopup.tsx
  src/components/organisms/UserDetails.tsx
  src/hooks/use-matching-room.ts
  src/hooks/use-projects.ts
  src/types/index.ts
  src/types/project.ts
Labels: ✨ feature

#141 Authorization 로직 변경
  src/app/deregister/page.tsx
  src/app/layout.tsx
  src/app/login-guard.tsx
  src/app/matching/page.tsx
  src/app/mypage/page.tsx
  src/app/projects/page.tsx
  src/app/signup-guard.tsx
  src/app/team-recommend/page.tsx
  src/components/atoms/Link.tsx
  src/components/molecules/HeaderLoginBlock.tsx
  src/components/molecules/HeaderNav.tsx
  src/components/templates/LoginPopup.tsx
  src/entities/api-error.ts
  src/stores/index.ts
  src/stores/login-guard.ts
Labels: 🛠️ refactor

#143 에러 발생 시 재시도 없애기
  src/components/templates/LoginCallback.tsx
  src/hooks/use-policy-agrees.ts
  src/hooks/use-user.ts
Labels: 🐛 bug

#150 fix: Update page parameter in use-recommend.ts to use index directly
  src/hooks/use-recommend.ts
Labels: 🐛 bug

#162 refactor: Update fetch base URL to use environment variable
  .env.example
  src/utilities/fetch.ts
  src/utilities/socket.ts
Labels: 🛠️ refactor

#167 매칭페이지 버튼 수정
  src/app/login-guard.tsx
  src/components/atoms/Link.tsx
  src/components/molecules/MatchingButtons.tsx
  src/components/molecules/MatchingTalkBackground.tsx
  src/components/molecules/MatchingTitle.tsx
  src/components/molecules/matching/MatchingButtons.tsx
  src/components/organisms/MatchingChatRoom.tsx
  src/components/organisms/MatchingRegister.tsx
  src/components/organisms/MatchingWaiting.tsx
  src/components/templates/Matching.tsx
  src/entities/api-error.ts
  src/entities/index.ts
  src/hooks/use-matching.ts
  src/types/api-error.ts
  src/types/index.ts
Labels: 🐛 bug

#168 체크박스 수정
  src/components/atoms/CheckBox.tsx
  src/components/atoms/Icons.tsx
Labels: 🐛 bug

#174 헤더 프로필 모달 너비 조정
  src/components/atoms/Icons.tsx
  src/components/molecules/HeaderMenuModal.tsx
  src/components/molecules/HeaderUserBlock.tsx
  src/components/organisms/ProfileBlock.tsx
Labels: 🛠️ refactor

#170 마이페이지 버그 수정
  src/components/molecules/MyPage/RegisterPortfolioBlock.tsx
  src/components/molecules/MyPage/TechSelectBlock.tsx
  src/components/organisms/MyPage/MemberInfoEdit.tsx
  src/components/organisms/MyPage/PortfolioEdit.tsx
  src/components/organisms/MyPage/PortfolioInformation.tsx
Labels: 🐛 bug

#169 회원가입 화면 모바일 화면 최적화
  src/app/layout.tsx
  src/assets/icons/arrow-forward-outlined.svg
  src/components/atoms/Divider.tsx
  src/components/molecules/Policies.tsx
  src/components/molecules/PositionCard.tsx
  src/components/molecules/SignUpProfileUpdateHeader.tsx
  src/components/organisms/SignUpCompletePopup.tsx
  src/components/organisms/SignUpProfileCreationPopup.tsx
  src/components/organisms/SignUpProfileUpdatePopup.tsx
  src/components/organisms/SignUpTermsPopup.tsx
  src/components/organisms/sign-up/PositionSelection.tsx
  src/components/organisms/sign-up/ProfileDetailsSubmission.tsx
  src/components/organisms/sign-up/TimeAvailabilitySubmission.tsx
  src/components/organisms/sign-up/ToolAvailabilitySubmission.tsx
  src/utilities/index.ts
  src/utilities/styles.ts
Labels: 🐛 bug, 🛠️ refactor

#177 `<Footer />` 로고 수정
  src/assets/icons/index.ts
  src/assets/icons/logo.svg
  src/assets/logo.svg
  src/assets/logos/index.ts
  src/assets/logos/signature.svg
  src/assets/logos/signature_monochrome.svg
  src/assets/logos/symbol.svg
  src/components/atoms/FitLogo.tsx
  src/components/atoms/Icons.tsx
  src/components/molecules/HeaderLogo.tsx
  src/components/molecules/SignUpTermsHeader.tsx
  src/components/organisms/FooterContent.tsx
Labels: 🐛 bug

#179 프로젝트가 없을 때 화면 개선
  src/components/organisms/EmptyProjectList.tsx
  src/components/organisms/ProjectList.tsx
  src/components/templates/Projects.tsx
Labels: ✨ feature

#180 채팅창 공지사항 텍스트 표시
  src/components/molecules/NoticeBubble.tsx
  src/hooks/use-chat.ts
Labels: 🐛 bug

#185 마이페이지에서 포트폴리오가 사라지던 버그 수정
  src/components/atoms/MyPage/PortfolioFileBlock.tsx
  src/components/templates/MyPage/InfoEditSection.tsx
Labels: 🐛 bug

#186 아이콘 크기 조정
  src/components/atoms/Icons.tsx
  src/components/atoms/Select.tsx
Labels: 🐛 bug

#189 멋진 로딩 컴포넌트
  src/app/globals.css
  src/components/atoms/Loading.tsx
  src/stories/Loading.stories.ts
Labels: ✨ feature

#183 팀원 추천 페이지 버그 수정
  src/components/organisms/TeamRecommend/RecommendFilterBlock.tsx
  src/components/organisms/UserDetails.tsx
  src/components/templates/TeamRecommend.tsx
  src/types/index.ts
  src/types/link.ts
  src/utilities/icon.ts
Labels: 🐛 bug

#191 dependency: Add react-toastify@^10.0.5
  .pnp.cjs
  package.json
  src/app/layout.tsx
  src/utilities/fetch.ts
  yarn.lock
Labels: ✨ feature

#190 `reportable` 처리
  src/components/atoms/Tooltip.tsx
  src/components/molecules/ChatParticipant.tsx
  src/components/molecules/ChatPositionGroup.tsx
  src/hooks/use-projects.ts
  src/types/chat.ts
  src/types/index.ts
  src/types/project.ts
Labels: ✨ feature

#182 알림 기능 추가
  src/components/atoms/AlarmBlock.tsx
  src/components/molecules/HeaderAlarmBlock.tsx
  src/components/molecules/HeaderUserBlock.tsx
  src/hooks/use-alarm.ts
  src/types/alarm.ts
  src/types/index.ts
  src/utilities/alarm-replace-text.ts
Labels: ✨ feature

#211 로딩 아이콘 수정
  src/components/atoms/Loading.tsx
  src/stories/Loading.stories.tsx
Labels: 🛠️ refactor

#213 `Toastify` 조용히 시키기
  src/utilities/fetch.ts
Labels: 🐛 bug

#197 로딩 애니메이션 오류 수정
  src/components/atoms/Loading.tsx
  src/stories/Loading.stories.tsx
Labels: 🐛 bug

#212 로그아웃 시 캐시된 모든 데이터 삭제
  src/components/atoms/Link.tsx
  src/components/molecules/HeaderMenuModal.tsx
Labels: 🛠️ refactor

#207 fix, 로그아웃 시 메인으로 이동하게 수정 및 새로고침되게 수정
  src/components/atoms/Link.tsx
  src/components/molecules/HeaderMenuModal.tsx
Labels: 🐛 bug

#214 이메일 유저이름과 도메인 통합시키기
  src/components/organisms/MyPage/MemberInfoEdit.tsx
  src/components/templates/MyPage/InfoEditSection.tsx
Labels: 🛠️ refactor

#217 모든 유저가 준비 상태거나 호스트면 시작하기 버튼 활성화
  src/components/molecules/MatchingButtons.tsx
Labels: 🐛 bug

#218 소켓으로 전송되는 채팅창 컨트롤 메시지 처리하기
  src/app/projects/layout.tsx
  src/app/projects/page.tsx
  src/components/molecules/ChatBubbles.tsx
  src/components/molecules/ControlBubble.tsx
  src/components/organisms/ProjectChatRoom.tsx
  src/components/organisms/ProjectList.tsx
  src/components/templates/Projects.tsx
  src/types/index.ts
  src/types/message.ts
  src/utilities/message.ts
Labels: ✨ feature

#222 메시지 버블 시간 처리하는 로직 수정
  next.config.js
  src/components/molecules/ChatBubble.tsx
  src/components/molecules/ChatParticipant.tsx
Labels: 🐛 bug

#224 소켓 데이터 처리
  src/components/molecules/ChatBubbles.tsx
  src/hooks/use-chat.ts
  src/utilities/message.ts
Labels: 🐛 bug

#227 `ControlMessage` 를 `NoticeMessage` 로 통합
  src/components/molecules/ChatBubbles.tsx
  src/components/molecules/ControlBubble.tsx
  src/components/molecules/NoticeBubble.tsx
  src/types/index.ts
  src/types/message.ts
  src/utilities/message.ts
Labels: 🐛 bug
