Repository Team-Crops/fit-web, pull requests merged in 2024-05, with the labels that each got.

#84 회원가입 시 포지션 선택 후 진행할 수 없음
  src/components/organisms/SignUpProfileCreationPopup.tsx
Labels: 🐛 bug

#82 로그인 후 상태 업데이트 문제
  src/app/login-guard.tsx
  src/components/templates/LoginCallback.tsx
  src/stores/auth.ts
Labels: 🐛 bug

#87 사용 가능 기술 선택 불가능 문제 해결
  src/components/organisms/sign-up/ToolAvailabilitySubmission.tsx
Labels: 🐛 bug

#90 `policies` 와 `policyData` 합치기
  src/app/login-guard.tsx
  src/app/policy/[type]/page.tsx
  src/components/molecules/Policies.tsx
  src/components/organisms/SignUpTermsPopup.tsx
  src/components/templates/Policy/PolicyContent.tsx
  src/entities/index.ts
  src/entities/policy.ts
  src/hooks/use-policy-agrees.ts
  src/types/policy.ts
Labels: 🛠️ refactor

#85 이용약관 및 개인정보처리방침 페이지 제작
  src/app/login-guard.tsx
  src/app/policy/[type]/page.tsx
  src/components/molecules/Policies.tsx
  src/components/organisms/Policy/NestedList.tsx
  src/components/organisms/SignUpTermsPopup.tsx
  src/components/templates/Policy/PolicyContent.tsx
  src/entities/index.ts
  src/entities/policy.ts
  src/hooks/use-policy-agrees.ts
  src/types/policy.ts
Labels: ✨ feature

#91 feat, mypage api 연동 및 모든 기능 추가
  src/assets/icons/facebook.svg
  src/assets/icons/github.svg
  src/assets/icons/index.ts
  src/assets/icons/linkedIn.svg
  src/assets/icons/tistory.svg
  src/assets/icons/velog.svg
  src/components/atoms/CheckBox.tsx
  src/components/atoms/Icons.tsx
  src/components/atoms/MyPage/PortfolioFileBlock.tsx
  src/components/atoms/MyPage/PortfolioTicket.tsx
  src/components/atoms/Select.tsx
  src/components/molecules/HeaderUserBlock.tsx
  src/components/molecules/MyPage/PositionBadge.tsx
  src/components/molecules/MyPage/RegisterPortfolioBlock.tsx
  src/components/molecules/MyPage/TechSelectBlock.tsx
  src/components/organisms/MyPage/ActivityEdit.tsx
  src/components/organisms/MyPage/ActivityInformation.tsx
  src/components/organisms/MyPage/MemberInfoEdit.tsx
  src/components/organisms/MyPage/MemberInformation.tsx
  src/components/organisms/MyPage/PolicyInformation.tsx
  src/components/organisms/MyPage/PortfolioInformation.tsx
  src/components/organisms/ProfileBlock.tsx
  src/components/templates/MyPage/InfoEditSection.tsx
  src/components/templates/MyPage/MyInfoSection.tsx
  src/components/templates/MyPage/ProfileSection.tsx
  src/hooks/use-file.ts
  src/stores/tempAuth.ts
  src/types/file.ts
  src/utilities/career-text-value-match.ts
Labels: ✨ feature

#92 feat `team-recommend` Page
  next.config.js
  src/assets/icons/clip-bold.svg
  src/assets/icons/clip.svg
  src/assets/icons/index.ts
  src/assets/icons/link.svg
  src/assets/icons/logout.svg
  src/assets/icons/user-line.svg
  src/components/atoms/Icons.tsx
  src/components/atoms/UserProfile.tsx
  src/components/molecules/HeaderMenuModal.tsx
  src/components/molecules/HeaderUserBlock.tsx
  src/components/molecules/MyPage/TechSelectBlock.tsx
  src/components/molecules/TeamRecommend/DataBlock.tsx
  src/components/molecules/TeamRecommend/Filter.tsx
  src/components/molecules/TeamRecommend/TechSelect.tsx
  src/components/organisms/MyPage/PortfolioEdit.tsx
  src/components/organisms/ProfileBlock.tsx
  src/components/organisms/TeamRecommend/RecommendFilterBlock.tsx
  src/components/organisms/TeamRecommend/UserDataCard.tsx
  src/components/organisms/TeamRecommend/UserDetailModal.tsx
  src/components/templates/MyPage/InfoEditSection.tsx
  src/components/templates/TeamRecommend/RecommendFilter.tsx
  src/components/templates/TeamRecommend/UserCardList.tsx
  src/hooks/use-recommend.ts
  src/hooks/use-user.ts
  src/stores/recommend.ts
Labels: ✨ feature

#93 유저 데이터 정보가 새로고침 시 사라지는 버그 수정
  src/app/login-guard.tsx
  src/components/organisms/HeaderContent.tsx
  src/stores/auth.ts
  src/utilities/session.ts
Labels: 🐛 bug

#95 약관 동의 안되던 버그 수정
  src/components/organisms/SignUpProfileCreationPopup.tsx
  src/components/organisms/SignUpTermsPopup.tsx
Labels: 🐛 bug

#97 fix, 포트폴리오 삭제 안되는 버그 수정
  src/components/templates/MyPage/InfoEditSection.tsx
Labels: 🐛 bug

#99 첫 회원가입 사용 가능한 툴에서 position 잘리는 문제 해결
  src/components/organisms/sign-up/ToolAvailabilitySubmission.tsx
Labels: 🐛 bug

#104 `getToken` 함수 수정
  .env.example
  src/utilities/session.ts
Labels: 🐛 bug

#102 `.env.example` 파일 추가
  .env.example
Labels: 💁 suggestion

#107 Add createdAt field to Message interface and useChatMessagesQuery
  src/components/molecules/ChatToolbox.tsx
Labels: 🐛 bug

#111 Fix UTC offset in ChatToolbox component
  src/components/molecules/ChatBubble.tsx
  src/components/molecules/ChatToolbox.tsx
  src/components/organisms/MatchingChatRoom.tsx
  src/hooks/use-matching-room.ts
Labels: 🐛 bug

#110 chat plain Time 오류 수정
  src/components/molecules/ChatToolbox.tsx
Labels: 🐛 bug

#113 방장일 때 매칭 준비 버튼 대신 매칭 완료 버튼 보이기
  src/components/organisms/MatchingChatRoom.tsx
  src/hooks/use-matching-room.ts
Labels: 🐛 bug

#123 로그인 시 유저 정보 요청하기
  src/components/organisms/HeaderContent.tsx
  src/components/templates/LoginCallback.tsx
Labels: 🐛 bug

#129 채팅 이미지 받기 기능 추가
  src/components/molecules/ChatBubble.tsx
  src/components/molecules/ChatBubbles.tsx
  src/components/molecules/ChatToolbox.tsx
  src/components/molecules/NoticeBubble.tsx
  src/types/index.ts
  src/types/message.ts
  src/utilities/index.ts
  src/utilities/message.ts
Labels: ✨ feature
