Repository Team-Crops/fit-web, pull requests merged in 2024-07, with the labels that each got.

#232 메시지 형식에 `CANCEL_READY` 추가
  src/types/message.ts
Labels: ✨ feature

#233 채팅 캐시 관련 버그 수정
  .eslintrc.json
  .pnp.cjs
  package.json
  src/app/signup-guard.tsx
  src/components/atoms/CheckBox.tsx
  src/components/atoms/FitLogo.tsx
  src/components/atoms/Icons.tsx
  src/components/atoms/Label.tsx
  src/components/atoms/Loading.tsx
  src/components/atoms/MouseDetector.tsx
  src/components/atoms/MyPage/PortfolioTicket.tsx
  src/components/atoms/SocialLoginButton.tsx
  src/components/atoms/Text.tsx
  src/components/molecules/ChatBubbles.tsx
  src/components/molecules/ChatToolbox.tsx
  src/components/molecules/HeaderAlarmBlock.tsx
  src/components/molecules/MyPage/TechSelectBlock.tsx
  src/components/molecules/NoticeBubble.tsx
  src/components/molecules/PositionCard.tsx
  src/components/molecules/TeamRecommend/TechSelect.tsx
  src/components/organisms/Chat.tsx
  src/components/organisms/ChatParticipants.tsx
  src/components/organisms/ChatRoom.tsx
  src/components/organisms/MatchingInfo/MatchingSequenceSwiper.tsx
  src/components/organisms/MatchingRegister.tsx
  src/components/organisms/MyPage/ActivityEdit.tsx
  src/components/organisms/MyPage/MemberInfoEdit.tsx
  src/components/organisms/MyPage/PortfolioInformation.tsx
  src/components/organisms/ProjectChatRoom.tsx
  src/components/organisms/SignUpCompletePopup.tsx
  src/components/organisms/SignUpProfileUpdatePopup.tsx
  src/components/organisms/SignUpTermsPopup.tsx
  src/components/organisms/TeamRecommend/RecommendFilterBlock.tsx
  src/components/organisms/sign-up/ProfileDetailsSubmission.tsx
  src/components/templates/LoginCallback.tsx
  src/entities/policy.ts
  src/hooks/index.ts
  src/hooks/use-chat-id.ts
  src/hooks/use-chat-users.ts
  src/hooks/use-chat.ts
  src/hooks/use-control-message-handler.ts
  src/hooks/use-matching.ts
  src/hooks/use-notice-message-handler.ts
  src/hooks/use-presigned-url.ts
  src/hooks/use-projects.ts
  src/stores/chat.ts
  src/stores/index.ts
  src/types/api-error.ts
  src/types/matching.ts
  src/types/message.ts
  src/utilities/index.ts
  src/utilities/matching.ts
  src/utilities/message.ts
  src/utilities/socket.ts
  svgr.d.ts
  tsconfig.json
  yarn.lock
Labels: 🐛 bug, 🛠️ refactor

#235 메인페이지 버튼 링크 수정
  src/components/organisms/main/InfoMatchingBlock.tsx
  src/components/organisms/main/MyProjectBlock.tsx
  src/components/organisms/main/RecommendBlock.tsx
Labels: 🐛 bug, 🛠️ refactor

#238 회원가입 할 때 프로젝트 경험 수 선택하지 않아도 기본으로 없음이 들어가게 변경
  src/components/atoms/Select.tsx
  src/components/organisms/sign-up/TimeAvailabilitySubmission.tsx
Labels: 🐛 bug

#242 채팅방 상태가 무한 새로고침되는 문제
  package.json
  src/components/molecules/ChatBubbles.tsx
  src/hooks/use-chat.ts
Labels: 🐛 bug

#243 Add 'FORCED_OUT' type to Message and NoticeMessage interface
  src/types/message.ts
  src/utilities/message.ts
Labels: 🐛 bug

#248 팀원 추천 디자인 변경 반영
  src/components/molecules/MyPage/PositionBadge.tsx
  src/components/molecules/TeamRecommend/TechSelect.tsx
  src/components/organisms/TeamRecommend/DibsFilterBlock.tsx
  src/components/organisms/TeamRecommend/RecommendFilterBlock.tsx
  src/components/templates/TeamRecommend/RecommendFilter.tsx
Labels: 🛠️ refactor

#241 스스로 강퇴 못하게 하기
  src/components/molecules/ChatPositionGroup.tsx
Labels: 🐛 bug

#249 프로젝트 카드 정리
  src/components/molecules/ChatBubble.tsx
  src/components/molecules/ProjectSummary.tsx
  src/utilities/format-date-time.ts
Labels: 🐛 bug

#251 프로젝트 페이지 디자인 개선
  src/components/organisms/ProjectList.tsx
Labels: 🐛 bug

#253 채팅 입력창 배경 추가
  src/components/molecules/ChatToolbox.tsx
  src/components/organisms/Chat.tsx
Labels: 🐛 bug

#256 `favicon.ico` 업데이트
  src/app/favicon.ico
  src/app/layout.tsx
Labels: ✨ feature

#246 Select 버그 수정
  src/components/atoms/Select.tsx
Labels: 🐛 bug
