Repository Team-Crops/fit-web, pull requests merged in 2024-03, with the labels that each got.

#51 `<Select />` 라벨 초기화
  src/assets/icons/arrow-down.svg
  src/assets/icons/arrow-forward-outlined.svg
  src/assets/icons/camera.svg
  src/assets/icons/emoji-fire.svg
  src/assets/icons/emoji-holding-back-tears.svg
  src/assets/icons/index.ts
  src/assets/icons/info.svg
  src/components/atoms/Icons.tsx
  src/components/atoms/Select.tsx
Labels: 🐛 bug

#52 MyPage View 제작
  public/images/tooltip.svg
  public/강아지.jpeg
  src/app/mypage/page.tsx
  src/assets/icons/clip.svg
  src/assets/icons/link.svg
  src/assets/icons/pencil.svg
  src/assets/icons/plus.svg
  src/assets/icons/upload.svg
  src/components/atoms/Icons.tsx
  src/components/atoms/Input.tsx
  src/components/atoms/MyPage/PortfolioFileBlock.tsx
  src/components/atoms/MyPage/PortfolioTicket.tsx
  src/components/atoms/Select.tsx
  src/components/molecules/MyPage/BasicInfo.tsx
  src/components/molecules/MyPage/BasicInfoEdit.tsx
  src/components/molecules/MyPage/MyInfoBlock.tsx
  src/components/molecules/MyPage/MyPageGridBlock.tsx
  src/components/molecules/MyPage/PositionBadge.tsx
  src/components/molecules/MyPage/RegisterPortfolioBlock.tsx
  src/components/molecules/MyPage/TechSelectBlock.tsx
  src/components/organisms/MyPage/ActivityEdit.tsx
  src/components/organisms/MyPage/ActivityInformation.tsx
  src/components/organisms/MyPage/MemberInfoEdit.tsx
  src/components/organisms/MyPage/MemberInformation.tsx
  src/components/organisms/MyPage/PolicyInformation.tsx
  src/components/organisms/MyPage/PortfolioEdit.tsx
  src/components/organisms/MyPage/PortfolioInformation.tsx
  src/components/organisms/ProfileBlock.tsx
  src/components/templates/MyPage/InfoEditSection.tsx
  src/components/templates/MyPage/MyInfoSection.tsx
  src/components/templates/MyPage/ProfileSection.tsx
Labels: ✨ feature

#55 Update TypeScript, ESLint, Prettier, and add build workflow
  .github/workflows/build.yml
  .github/workflows/eslint.yml
  .pnp.cjs
  .yarn/sdks/eslint/package.json
  .yarn/sdks/prettier/package.json
  package.json
  src/app/login/callback/[platform]/page.tsx
  src/stories/Toggle.stories.tsx
  yarn.lock
Labels: 🐛 bug

#56 Add GitHub deployment creation script
  .github/workflows/build.yml
  .github/workflows/dev-deployment.yml
Labels: ⚙️ cicd

#57 매칭 페이지 구현
  next.config.js
  src/app/globals.css
  src/app/login-guard.tsx
  src/app/matching/page.tsx
  src/assets/icons/image.svg
  src/assets/icons/index.ts
  src/assets/icons/progress.svg
  src/assets/icons/upload.svg
  src/assets/images/index.ts
  src/assets/images/matching-page-background-1.png
  src/assets/images/matching-page-doughnut.png
  src/components/atoms/Badge.tsx
  src/components/atoms/ConfirmationDialog.tsx
  src/components/atoms/Icons.tsx
  src/components/atoms/ProgressBar.tsx
  src/components/atoms/UserProfile.tsx
  src/components/molecules/HeaderNav.tsx
  src/components/molecules/ProfileCard.tsx
  src/components/molecules/ProgressBar.tsx
  src/components/molecules/RegionSelect.tsx
  src/components/molecules/SignupProgressBar.tsx
  src/components/molecules/TalkBubble.tsx
  src/components/molecules/TalkPositionGroup.tsx
  src/components/molecules/matching/MatchingButtons.tsx
  src/components/molecules/matching/MatchingTalkBackground.tsx
  src/components/molecules/matching/MatchingTitle.tsx
  src/components/organisms/login/ActivityInfoPopup.tsx
  src/components/organisms/login/PersonalInfoPopup.tsx
  src/components/organisms/login/PoliciesPopup.tsx
  src/components/organisms/login/PositionInfoPopup.tsx
  src/components/organisms/login/SkillInfoPopup.tsx
  src/components/organisms/login/UserInfoPopup.tsx
  src/components/organisms/matching/MatchingProfile.tsx
  src/components/organisms/matching/MatchingQueued.tsx
  src/components/organisms/matching/MatchingTalk.tsx
  src/components/templates/Matching.tsx
  src/entities/user.ts
  src/redux/api.ts
  src/redux/features/matching/slice.ts
  src/redux/features/region/api.ts
  src/redux/features/skill-set/api.ts
  src/redux/store.ts
Labels: ✨ feature

#58 `MatchingInfo` 페이지 구현
  public/images/matchingInfo/chat1.svg
  public/images/matchingInfo/chat2.svg
  public/images/matchingInfo/circle.svg
  public/images/matchingInfo/notebook.svg
  public/images/matchingInfo/profile.svg
  public/images/matchingInfo/shoppingback.svg
  src/app/matchingInfo/page.tsx
  src/components/atoms/Text.tsx
  src/components/molecules/MainDescriptionCard.tsx
  src/components/organisms/MatchingInfo/MatchingInfoImage.tsx
  src/components/organisms/MatchingInfo/MatchingSequenceSwiper.tsx
  src/components/organisms/main/MyProjectBlock.tsx
  src/components/templates/MatchingInfo/MatchingInfoSection.tsx
  src/components/templates/MatchingInfo/MatchingSequence.tsx
Labels: ✨ feature

#63 `secondary` 버튼 글씨 색상 수정
  src/components/atoms/Button.tsx
  src/stories/Button.stories.ts
Labels: 🐛 bug

#65 main page에 있는 swiper 이미지 위치 조정
  src/components/organisms/main/InfoMatchingBlock.tsx
Labels: 🐛 bug

#71 개발환경 도커
  .dockerignore
  Dockerfile.development
  README.md
  docker-compose.yaml
Labels: 🛠️ refactor
