Repository Team-Crops/fit-web, pull requests merged in 2024-02, with the labels that each got.

#39 Feature `<Footer />` Component
  src/app/page.tsx
  src/assets/icons/instagram.svg
  src/components/atoms/Icons.tsx
  src/components/organisms/FooterContent.tsx
  src/components/templates/Footer.tsx
Labels: ✨ feature

#43 상위 컴포넌트에서 정의한 `color` CSS 속성을 `<Txt />` 가 상속받지 못하는 버그 수정
  src/components/atoms/Text.tsx
Labels: 🐛 bug

#44 `<Txt />` 컴포넌트에 `color` 속성이 적용되지 않는 문제 해결
  src/components/atoms/Text.tsx
Labels: 🐛 bug

#46 `<Input />`에서 `width`를 props로 받을 수 있게 추가
  src/components/atoms/Input.tsx
Labels: 🛠️ refactor

#48 <Select /> 버그 및 추가 세가지
  src/components/atoms/Select.tsx
Labels: 🐛 bug
